title: Sweet scroll
hero_image: images/banner.png
description: Learn to create a recipe web page using the parallax scroll technique!
duration: 3
technologies: html-css-javascript
software: html-css-javascript
version: 4.0.1
listed: true
copyedit: true
ingredient: false
last_tested: "2019-05-03"
steps:
  - title: Introduction
  - title: Get started
  - title: Add parallax scroll
  - title: Add captions
  - title: "Challenge: add more sections"
    challenge: true
  - title: Make your web page look great on mobile devices
  - title: "Challenge: create a cookbook"
    challenge: true
