title: Sweet scroll
hero_image: images/banner.png
description: Learn to create a recipe web page using the parallax scroll technique!
version: 4
listed: false
copyedit: false
ingredient: false
last_tested: "2019-03-07"
steps:
  - title: Introduction
  - title: Get started
  - title: Add parallax scroll
  - title: Add captions
  - title: "Challenge: add more sections"
    challenge: true
  - title: Make your web page look great on mobile devices
  - title: "Challenge: create a cookbook"
    challenge: true
