title: Sweet scroll
hero_image: images/banner.png
description: Learn to create a recipe page using the parallax scroll technique!
version: 4
listed: false
copyedit: false
ingredient: false
last_tested: "2019-03-07"
steps:
  - title: Introduction
  - title: Getting started
  - title: Parallax scroll
  - title: Add captions
  - title: "Challenge: more sections"
    challenge: true
  - title: Handling mobile and tablet screens
  - title: "Challenge: create a cookbook"
    challenge: true
